<?php 

/**
 * Wise Chat admin appearance settings tab class.
 *
 * @version 1.0
 * @author Marcin Ławrowski <marcin.lawrowski@gmail.com>
 */
class WiseChatAppearanceTab extends WiseChatAbstractTab {

	public function getFields() {
		return array(
			array('theme', 'Theme', 'selectCallback', 'string', 'Current theme', WiseChatThemes::getAllThemes()),
			array('background_color', 'Background Color <br />(messages window)', 'colorFieldCallback', 'string', 'Background color of the messages window'),
			array('background_color_input', 'Background Color <br />(message input field)', 'colorFieldCallback', 'string', 'Background color of the message input field'),
			array('text_color', 'Text Color', 'colorFieldCallback', 'string', 'Text color of the messages, inputs and labels'),
			array('text_color_logged_user', 'Text Color<br />(logged in user)', 'colorFieldCallback', 'string', 'Color of the messages typed by a logged in user'),
			array('chat_width', 'Width', 'stringFieldCallback', 'string', 'Width of the chat, a raw number or a number with unit (px or %) is allowed, default: 100%'),
			array('chat_height', 'Height', 'stringFieldCallback', 'string', 'Height of the chat, a raw number or a number with unit (px or %) is allowed, default: 200px'),
			array('show_message_submit_button', 'Show Submit Button', 'booleanFieldCallback', 'boolean', 'Displays the submit button next to the message input field, might be useful on mobile devices'),
			array('show_user_name', 'Show User Name', 'booleanFieldCallback', 'boolean', 'Shows the name of the current user near the input field'),
			array('link_wp_user_name', 'Link User Name', 'booleanFieldCallback', 'boolean', 'Converts user name in each message into a link. By default the link directs to the author\'s page. Only messages sent by WordPress users are taken into account. If you would like to link every user name provide a template for the link (see option below).'),
			array('link_user_name_template', 'Link User Name Template', 'stringFieldCallback', 'string', 'A template of the URL used to construct a link from user name in each message. While creating the template you can use the following dynamic variables: id, username, displayname. <br />Example: http://my.website.com/users/{username}/profile'),
			array('allow_change_user_name', 'Allow To Change User Name', 'booleanFieldCallback', 'boolean', 'Permits an anonymous user to change his/her name displayed on the chat'),
			array('emoticons_enabled', 'Show Emoticons', 'booleanFieldCallback', 'boolean', 'Shows emoticons'),
			array('multiline_support', 'Multiline Messages', 'booleanFieldCallback', 'boolean', 'Permits multiline messages. Submit button has to be enabled in order to send a message.'),
			array('show_users', 'Show Users List', 'booleanFieldCallback', 'boolean', 'Shows users currently visiting the channel'),
			array('show_users_counter', 'Show Users Counter', 'booleanFieldCallback', 'boolean', 'Shows amount of users visiting current channel'),
			array('input_controls_location', 'Input Controls Location', 'selectCallback', 'string', 'Location of the input field, submit button and customizations panel section', WiseChatAppearanceTab::getInputFieldLocation()),
			array('messages_order', 'Messages Order', 'selectCallback', 'string', 'Sorting order of the messages', WiseChatAppearanceTab::getSortingOrder()),
			array('messages_time_mode', 'Message Time Mode', 'selectCallback', 'string', 'Format of the date and time displayed next to each message', WiseChatAppearanceTab::getTimeModes()),
			array('enable_title_notifications', 'Enable Title Notifications', 'booleanFieldCallback', 'boolean', 'Shows notifications in browser\'s title when new messages arrives and the browser window is hidden / inactive'),
			array('sound_notification', 'Sound Notification', 'selectCallback', 'string', 'Plays a sound when new messages arrives', WiseChatAppearanceTab::getNotificationSounds()),
			array('allow_mute_sound', 'Allow To Mute Sounds', 'booleanFieldCallback', 'boolean', 'Permits an user to mute all sounds generated by the chat'),
			array('custom_styles', 'Custom CSS Styles', 'multilineFieldCallback', 'multilinestring', 'Custom CSS styles for the chat, valid CSS syntax is required.'),
		);
	}
	
	public function getDefaultValues() {
		return array(
			'theme' => '',
			'background_color' => '',
			'background_color_input' => '',
			'text_color' => '',
			'text_color_logged_user' => '',
			'chat_width' => '100%',
			'chat_height' => '200px',
			'show_user_name' => 0,
			'link_wp_user_name' => 0,
			'link_user_name_template' => '',
			'show_message_submit_button' => 0,
			'allow_change_user_name' => 0,
			'emoticons_enabled' => 1,
			'multiline_support' => 0,
			'show_users' => 0,
			'show_users_counter' => 0,
			'input_controls_location' => '',
			'messages_order' => '',
			'custom_styles' => '',
			'enable_title_notifications' => '',
			'sound_notification' => '',
			'allow_mute_sound' => '',
			'messages_time_mode' => ''
		);
	}
	
	public function getParentFields() {
		return array(
			'link_user_name_template' => 'link_wp_user_name'
		);
	}
	
	public static function getTimeModes() {
		return array(
			'hidden' => 'Hidden',
			'' => 'Full',
			'elapsed' => 'Elapsed'
		);
	}
	
	public static function getInputFieldLocation() {
		return array(
			'' => 'Bottom',
			'top' => 'Top'
		);
	}
	
	public static function getSortingOrder() {
		return array(
			'' => 'Newest on the bottom',
			'descending' => 'Newest on the top'
		);
	}
	
	public static function getNotificationSounds() {
		return array(
			'' => 'Disabled',
			'sound-01' => 'Sound 1',
			'sound-02' => 'Sound 2',
			'sound-03' => 'Sound 3',
			'sound-04' => 'Sound 4'
		);
	}
}